### ISSUE TITLE
Mention CLI in readme

### ISSUE THREAD

**Issue by Nemo157** [purpliminal/rust-dotenv#104]
I was just about to open a ticket about providing a CLI, luckily I actually took a quick glance at the code and saw one already existed :smiley:. It'd be great to mention this in the readme, along with the command to install it.

(I would even be tempted to say that using the CLI should be the recommended approach in development environments, and normally test environments provide their own way to set env vars instead of requiring the application to do it itself, but debating that is probably a whole can of worms).

**Comment by Nemo157** [comment]
And after testing, the required install command is `cargo install dotenv --features cli`.

**Comment by purpliminal** [comment]
Closing this by #106; feel free to expand on it!
