### ISSUE TITLE
tests dir?

### ISSUE THREAD

**Issue by alicemaz** [purpliminal/rust-dotenv#25]
was messing around with the integration tests in prep for working on other issues and ran into this. looking for guidance, not sure what the proper way to do this is, given my relative newness at the language.

presently if you run `cargo test` from the project root, it doesn't run the integration tests. you have to be in `tests/`, and cargo creates a second build in that dir to run just those off of. I moved `main.rs` up a level, deleted `tests/src/` and `tests/Cargo.toml`. now doc/unit/integration tests all run from one command off one build from anywhere in the project, which seems desirable.

of course the integrations fail now because I messed with the hierarchy. so I changed `tests/main.rs` to this, which passes:

``` rust
extern crate dotenv;

use dotenv::*;
use std::env;
use std::path::Path;

#[test]
fn test_dotenv() {
    let new_path = Path::new("./tests");
    assert!(env::set_current_dir(&new_path).is_ok());

    dotenv().ok();
    assert_eq!(env::var("TESTKEY").unwrap(), "test_val");
}
```

good. problem is the second test now, testing from a child dir. tinkering with things a bit, it seems that (for reasons I do not quite understand) although tests are _run_ in parallel, they _share_ an environment. this means that changing `current_dir` in the second test can make the _first_ test fail.

basically, bog standard "shared mutable state in a multithreaded program" nightmare, every test becomes a race condition. for instance creating `tests/child/` and appending this to the above code...

``` rust
#[test]
fn make_test_fail() {
    let new_path = Path::new("./child");
    assert!(env::set_current_dir(&new_path).is_ok());
    let new_path2 = Path::new("..");
    assert!(env::set_current_dir(&new_path2).is_ok());
}
```

...fails _sometimes_.

so every test has to run under the assumption the dir may or may not have been changed. normally I'd just shrug and put "if last path fragment not tests set current dir ./tests else do nothing" at the top of everything and call it a day. obviously that can't be done with this project though, since literally what we need to test is the effects of varying current dirs, hierarchies, etc.

not sure how to proceed. my instincts say the simplest way might be to replace the call to `current_dir` on 141 with a call to our own function that returns `current_dir`, and stub that out in tests for whatever dir each test needs. this nixes the shared state problem, but I'm not sure about messing with the codebase itself to conform to affordances of the test runner. also I wonder if doing this runs counter to the very idea of integration testing. of course could add another test using `current_dir` but, I dunno. maybe there is a better way to deal with this that I am not aware of.

anyway. sorry for wall of text. thoughts?

**Comment by slapresta** [comment]
No need to apologise! Thank you for taking the effort to try this out and document it!

There is probably a way to force Cargo to run tests non-concurrently, but that feels like the wrong approach to the problem.

Stubbing out the filesystem state would be nice, but I would be wary of calling tests that use a stubbed filesystem _integration_ tests...

**Comment by mfpiccolo** [comment]
I am away from my computer at the moment and can join in soon but this may help. 
 In env;
RUST_TEST_THREADS=1

**Comment by mfpiccolo** [comment]
I am not sure moving the integration tests out of the test dir is the best approach.  I would almost prefer to move the unit tests into the tests dir and only run the test build there.  That may not be helpful with the issue you are describing though.  @alicemaz do you have a branch that you can push up with your changes so we can take a look?

**Comment by alicemaz** [comment]
meant I moved from `tests/src/` to `tests/`. pushed a branch with what I mean: https://github.com/slapresta/rust-dotenv/tree/test-wip

screenshot of the issue at present:
![screenshot - 12062015 - 06 27 30 pm](https://cloud.githubusercontent.com/assets/11409285/11616399/fba03d6a-9c47-11e5-967c-d353e6f1ff53.png)

**Comment by mfpiccolo** [comment]
This is perhaps not ideal but I added a before fn that sets the current_dir for each test to the tests dir.

https://github.com/slapresta/rust-dotenv/tree/mp-test-wip

**Comment by mfpiccolo** [comment]
@alicemaz Did you get a chance to look at the before fn from the commit I added?  It is not the best solution but it allows the tests to run in parallel.

**Comment by alicemaz** [comment]
sorry, was away for awhile. pushed to mp-test-wip. a new fun thing I have run into is that the shared environment makes it impossible to reliably clear loaded envs between tests. for this to work you must run `RUST_TEST_THREADS=1 cargo test`. ideally there would be someplace in Cargo.toml to set this so `cargo test` does the right thing but ¯\_(ツ)_/¯

**Comment by casey** [comment]
@purpliminal, can this be closed given the changes to integration tests in #80?

**Comment by purpliminal** [comment]
Sure thing!
