### ISSUE TITLE
Turn off the default features of error-chain to not force backtrace dependence on downstream crates

### ISSUE THREAD

**Issue by golddranks** [purpliminal/rust-dotenv#65]
The `error-chain` crate has as a default feature that enables the `backtrace` crate. I don't want backtraces to my errors, and even if I disable the default features of `error-chain`, it won't help because `dotenv` forces the features on.

It would be better to set the default-features off and let the user to decide whether to set them on or leave them off. Since the features in Cargo are only additive, this isn't possible if some of the dependencies decides to keep them on.

**Comment by golddranks** [comment]
I tried to champion a PR, but had some problems: https://www.reddit.com/r/rust/comments/6i480l/hey_rustaceans_got_an_easy_question_ask_here/dj3litd/

Basically, if `dotenv` wouldn't use `error-chain-derive`, we could just set `default-features` off, but because it uses, there's the attribute `error_chain(backtrace = "false")` that needs to be set on or off.

To be able to do that, it's possible to do:

    #[cfg_attr(not(feature = "backtrace"), error_chain(backtrace = "false"))]

But then again, that requires `dotenv` to have a feature `backtrace`, which should be always set to the same as the similar feature of `error-chain`, or else a compilation error occurs.

**Comment by golddranks** [comment]
Btw. a pull request now exists: https://github.com/purpliminal/rust-dotenv/pull/66

**Comment by purpliminal** [comment]
Thanks! I'll merge the PR and close this.
