### ISSUE TITLE
How to define vars with paths relative to the .env file?

### ISSUE THREAD

**Issue by Boscop** [purpliminal/rust-dotenv#71]
I have a file `.env` that contains e.g. `DATABASE_URL=app.db`, and it is read in several subdirs.
But the problem is, the path is interpreted as relative to the cwd where the .env file is read, **not** relative to the .env file, and the subdirs are on different levels so there is no way to express it in a relative path like `../app.db`.

How can I make the path relative to the location of the .env file? And, shouldn't that be the default?

**Comment by daboross** [comment]
I don't believe `dotenv` currently does anything at all with values in the .env files - it's unknown whether they are paths or just strings/numbers - and I don't think there's one sensible default to take here.

Perhaps this would be an extra API to add though? Some function to get an env variable resolved as a path, and relative to the .env file if it is a relative path.

**Comment by purpliminal** [comment]
Since #59, the `from_filename` and `dotenv` methods return a `PathBuf` representing the path of the `.env` file that was processed -- you could then append to it the `DATABASE_URL` value to interpret it relative to the `.env` file.

Please let me know if this solves your question!

**Comment by Boscop** [comment]
It doesn't solve my actual problem because I'm using diesel's `infer_schema!("dotenv:DATABASE_URL"); ` which doesn't post-process the env vars before interpreting them.

**Comment by purpliminal** [comment]
I guess `infer_schema!` could, when the database URL given refers to a file, evaluate it relative to the location of the file where the environment variable was fetched? But I don't think this is a good idea, in general. I think environment variables should be understood as local to the process you're spawning, and `.env` files should just be used as convenient ways to set your environment variables for a given project. Having it pre-process the environment variables seems strange to me. What do you think @sgrif?
