### ISSUE TITLE
Consider making .env variable iterator or vec available

### ISSUE THREAD

**Issue by casey** [purpliminal/rust-dotenv#74]
I would like to be able to load variables from a `.env` file, but would like to avoid putting them into the current process's environment, instead putting them into a child process's environment using `process::Command::env`.

Would it be possible to allow loading variables from a `.env` file, but only providing an iterator or vec of them, instead of loading them into the current process's environment?

**Comment by casey** [comment]
Hi there! Just wanted to ping this issue and see if you've had a chance to consider the request.

I'd be happy to supply a PR if it sounds reasonable.

**Comment by purpliminal** [comment]
Hi! Sorry for not replying earlier. Life's been kind of in the way lately.

The feature makes a lot of sense to me! It would enable using dotenv as a library for parsing `.env` files for more generic use cases.

If you opened a PR, that would be amazing! I feel like the easiest way to do this would be to split [`from_file`](https://github.com/purpliminal/rust-dotenv/blob/master/src/lib.rs#L187-L199) in two, separating file parsing and altering the process' environment.
