### ISSUE TITLE
Add casting helpers

### ISSUE THREAD

**Issue by eberkund** [purpliminal/rust-dotenv#86]
It would be nice it this library included helpers for casting into different types. It is very common to need to get a environment variable and cast it to a `u32` for example.

**Comment by imp** [comment]
Anything beyond what `std::str::parse` does?

**Comment by eberkund** [comment]
Pretty much what `std::str::parse` would do, my inspiration comes from [spf13/viper](https://github.com/spf13/viper#getting-values-from-viper)

**Comment by casey** [comment]
I'm inclined to say that that's out of scope for this library, `std::str::parse` does what you need and is pretty ergonomic:

I will say that it would be pretty cool if there you could use serde to do typesafe deserialization of `.env` variables into structs.

**Comment by daboross** [comment]
I think this would be a use case for the [`configure`](https://github.com/withoutboats/configure) crate.

It draws everything from env variables, so just running `dotenv::dotenv()` then loading the configuration in `configure` should work well.

**Comment by purpliminal** [comment]
I agree with @daboross and @casey: The purpose of this library is just to merge environment values from a file into the application's environment. Transformations on those values are outside the scope of this library.
